---

## Compact flash settings
cf_device: '/dev/sdb'
cf_partition: '/dev/sdb1'
cf_mount: '/mnt/cf'


# Debian packages to install
# (note that we don't do automatic dependancy checking)
debian_packages:
 - libc6
 - prelink
 - libasound2
 - libmad0
 - libfaad0
 - libogg0
 - libspeex1
 - libmpcdec3
 - rsync
 - libltdl3
 - libstdc++6
 - libattr1
 - libruby1.8
 - ruby1.8
 - irb1.8
 - ethtool


# Files to remove from the build root
unwanted_files:
 - '^/usr/include'
 - '^/usr/lib/gconv'
 - '^/usr/lib/pkgconfig'
 - '^/usr/lib/ruby/1.8/runit'
 - '^/usr/lib/ruby/1.8/soap'
 - '^/usr/lib/ruby/1.8/test'
 - '^/usr/lib/ruby/1.8/wsdl'
 - '^/usr/lib/ruby/1.8/xsd'
 - '^/usr/lib/ruby/1.8/xmlrpc'
 - '^/usr/share/doc'
 - '^/usr/share/locale'
 - '^/usr/share/man'
 - '^/usr/share/menu'
 - '\.la$'
