---

## Compact flash settings
cf_device: '/dev/sdb'
cf_partition: '/dev/sdb1'
cf_mount: '/mnt/cf'


# Debian packages to install
# (note that we don't do automatic dependancy checking)
debian_packages:
 - alsa-utils
 - ethtool
 - irb1.8
 - libasound2
 - libattr1
 - libc6
 - libfaad0
 - libgcc1
 - libgemplugin-ruby1.8
 - libiw29
 - libltdl3
 - libmad0
 - libmpcdec3
 - libogg0
 - libopenssl-ruby1.8
 - libruby1.8
 - libspeex1
 - libsqlite3-0
 - libsqlite3-ruby1.8
 - libssl0.9.8
 - libstdc++6
 - madwifi-tools
 - mongrel
 - prelink
 - rsync
 - ruby1.8
 - rubygems1.8
 - sqlite3
 - wireless-tools
 - zlib1g
 
# Files to remove from the build root
unwanted_files:
 - '^/usr/include'
 - '^/usr/lib/gconv'
 - '^/usr/lib/pkgconfig'
 - '^/usr/lib/ruby/1.8/runit'
 - '^/usr/lib/ruby/1.8/soap'
 - '^/usr/lib/ruby/1.8/webrick'
 - '^/usr/lib/ruby/1.8/wsdl'
 - '^/usr/lib/ruby/1.8/xmlrpc'
 - '^/usr/lib/ruby/1.8/xsd'
 - '^/usr/share/doc'
 - '^/usr/share/locale'
 - '^/usr/share/man'
 - '^/usr/share/menu'
 - '^/usr/share/lintian'
 - '\.la$'
