#!/bin/sh
#
# Update the local system using rsync
# The options should be the same as in install.pl
#

# Was the address of the rsyncd host given on command line?
if [ $1 ]; then
	RSYNC_HOST="$1"
else 
	RSYNC_HOST="rsync.aelius.com"
fi

echo "rsyncing from: $RSYNC_HOST"


# Re-mount filesystem Read-Write
remountrw

# Copy from host to local root filesystem
rsync \
	--verbose \
	--recursive \
	--links \
	--hard-links \
	--perms \
	--times \
	--exclude=.svn \
	"rsync://$RSYNC_HOST/lunchbox/" /

# Save the data to disk
sync

# Done, re-mount Read Only
remountro
