#!/bin/sh

# Mount /proc and /var
echo "> Mounting filesystems"
mount -a
chmod 0755 /var

# Create tmp dir on ramdisk
if [ ! -d /var/tmp ]; then
  echo "> Creating /var/tmp"
  mkdir /var/tmp
  chmod a+rwx /var/tmp
fi

# Create directories for webapp on ramdisk
if [ ! -d /var/lunchbox ]; then
  echo "> Creating /var/lunchbox"
  mkdir -p /var/lunchbox/db
  touch /var/lunchbox/db/production.sqlite3
  mkdir -p /var/lunchbox/log
  mkdir -p /var/lunchbox/cache
  mkdir -p /var/lunchbox/sessions
  chown -R webapp:lunchbox /var/lunchbox
fi

# Copy services directory to ramdisk
echo "> Copying services directory to /var/services"
cp -af /usr/service /var/service

# Set the hostname
echo "> Setting up basic networking"
hostname lunchbox
ifconfig lo up

# Needed by DHCP (Raw Packet socket address family)
modprobe af_packet

# Needed by rsync (Unix socket address family)
modprobe unix

# Create a default resolv.conf
echo "search aelius.com" > /var/resolv.conf
echo "nameserver 8.8.8.8" >> /var/resolv.conf

echo
echo "> Welcome to Lunch Box Radio OS"
echo
