#!/bin/sh

# Mount /proc and /var
echo "> Mounting filesystems"
/bin/mount -a
mkdir /var/tmp

# Copy services directory to ramdisk
echo "> Copying services directory to /var/services"
cp -af /usr/service /var/service

# Set the hostname
echo "> Setting up basic networking"
/bin/hostname giggi
/sbin/ifconfig lo up

# Needed by DHCP (Raw Packet socket address family)
modprobe af_packet

# Needed by rsync (Unix socket address family)
modprobe unix

# Create a default resolv.conf
echo "search giggi.org" > /var/resolv.conf
echo "nameserver 80.68.95.25" >> /var/resolv.conf

echo
echo "> Welcome to Giggi Radio OS"
echo
